### ISSUE TITLE
Bug: no exported member 'PublicProps'

### ISSUE THREAD

**Issue by dawidreedsy** [vuejs/test-utils#2317]
**Describe the bug**
After bumping @vue/test-utils from 2.4.3 to 2.4.4, i get the error:
```
vue-tsc --noEmit --project src/tsconfig.json

Error: node_modules/@vue/test-utils/dist/components/RouterLinkStub.d.ts(10,130): error TS2694: Namespace '"/node_modules/vue/dist/vue"' has no exported member 'PublicProps'.
Error: node_modules/@vue/test-utils/dist/vnodeTransformers/stubComponentsTransformer.d.ts(18,[12]
github: error TS2694: Namespace '"/node_modules/vue/dist/vue"' has no exported member 'PublicProps'.
Error: Process completed with exit code 2.
```

**To Reproduce**
Not sure it was building on previous version and type errors are coming from the `@vue/test-utils` lib

**Expected behavior**
Build properly

**Related information:**
```
  System:
    OS: macOS 14.1.2
    CPU: (10) x64 Apple M1 Max
    Memory: 962.70 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    @vue/test-utils: ^2.4.4 => 2.4.4
    vue: ^3.3.4 => 3.3.4

```
**Additional context**

**Comment by cexbrayat** [comment]
Hi @dawidreedsy 

That's strange. Have you tried updating to the latest Vue release (v3.4.15)?
If the problem persists, can you provide us a small repro online using https://stackblitz.com/github/vuejs/create-vue-templates/tree/main/typescript-vitest?file=src%2Fcomponents%2F__tests__%2FHelloWorld.spec.ts ? 

It only takes a few minutes, and we'll be able to take a look

**Comment by cexbrayat** [comment]
@dawidreedsy Did you manage to fix the issue after upgrading to the latest Vue version?

**Comment by cexbrayat** [comment]
Alright, let's close then
