### PR TITLE
feat: integrated `vue-component-type-helpers`

### LINKED ISSUE #1973: "vue-tsc" fails with "error TS2769: No overload matches this call" in "strict" mode
**Describe the bug**
`vue-tsc` fails with "error TS2769: No overload matches this call" in when "strict" mode is configured in "tsconfig.json".

If the `defineEmits` part in the component is removed `vue-tsc` doesn't complain. Seems that this issue is somehow related with Vue version 3.2.46.

**To Reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-nwzj9x?file=components%2FSlotComponent.vue,test%2FSlotComponent.test.ts,package.json&initialPath=__vitest

**Expected behavior**
`vue-tsc` does not fail for the example given.

### PR DESCRIPTION
**Pull request by johnsoncodehk**
Use `vue-component-type-helpers` instead of infer component props / slots from `DefineComponent`.

`vue-component-type-helpers` is simple in itself, but it behaves in line with `vue-component-meta`.

Fixes #1973

### CODE REVIEW

**Comment by johnsoncodehk** [comment]
I have removed node 14 test in this PR, because vue-tsc is given up node 14 support after v.1.3 (https://github.com/vuejs/language-tools/pull/2489).

**Review by lmiller1990 — APPROVED** [review]
Wow, great. Any recommendation for the release notes? Eg "Improve slot type inference when using TypeScript" would be correct?

Looks like this vastly simplifies the types, thanks!

File: src/index.ts [hunk 1]
```diff
@@ -25,5 +25,3 @@ export {
   MountingOptions,
   createWrapperError
 }
-
-export type { ComponentMountingOptions } from './mount'
```
Comment (freakzlike) [inline src/index.ts:29]: I think we should still export the type as it has been introduced with #2009. Should be type from here, right? https://github.com/vuejs/test-utils/blob/719549ddea62917629f7bc172a04694f8bde49d2/src/mount.ts#L38-L50

**Review by freakzlike — CHANGES_REQUESTED** [review]
I like it. Good work 👍

File: src/vueWrapper.ts [hunk 2]
```diff
@@ -75,14 +69,10 @@ function createVMProxy<T extends ComponentPublicInstance>(
 }
 
 export class VueWrapper<
-  T extends Omit<
-    ComponentPublicInstance,
-    '$emit' | keyof ComponentCustomProperties
-  > & {
-    $emit: (event: any, ...args: any[]) => void
-  } & ComponentCustomProperties = ComponentPublicInstance
+  T = any,
```
Comment (cexbrayat) [inline src/vueWrapper.ts:72]: Is it normal to not have an `extend` close here?

File: src/mount.ts [hunk 3]
```diff
@@ -1,150 +1,54 @@
...
+        | PatchSlot<ComponentSlots<T>[K]>
+        | string
+        | VNode
+        | VNode[]
+        | (new () => any)
+        | { template: string }
+    }
+    global?: GlobalMountOptions
+  }
+): VueWrapper<ComponentExposed<T> & ComponentProps<T>>
```
[the remark this answers is not in the document]
Comment (cexbrayat) [reply src/mount.ts:51]: OOC is there a way to type the vm to have all the component fields, and not only those exposed (as VTU exposes everything on `wrapper.vm` to simplify testing, see https://github.com/vuejs/test-utils/issues/972)

**Review by cexbrayat — COMMENTED** [review]
@johnsoncodehk Thanks for working on this ♥️

**Comment by cexbrayat** [comment]
@pikax If you have some time Carlos, it would be great to have your input as you worked on the original types

**Comment by cexbrayat** [comment]
@lmiller1990 As this has the potential to be fairly breaking (I hope not), we should cut an alpha release for this to give it a try when merged

File: src/index.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (lmiller1990) [reply src/index.ts:29]: Ah, true. Test Utils basically never has a breaking change, it would be great to avoid breaking other libraries.

**Comment by lmiller1990** [comment]
Hmm good point on the breaking change - it would be really ideal not to. Test Utils has *never* had a breaking change - and if it's just type definitions, this doesn't feel like a very compelling reason to break that pattern. I hope we can reassemble a kind of `ComponentMountOptions` type using `vue-component-type-helpers`?

File: src/mount.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (johnsoncodehk) [reply src/mount.ts:54]: Updated `renderToString`.

Exposing the template context can't be done from this PR alone, I don't know a reasonable way or if you have any ideas, you can open an issue in the volar repo and I will see what we can do.

File: src/index.ts (hunk 1 above)
Comment (johnsoncodehk) [reply src/index.ts]: Updated.

[the remark this answers is not in the document]
Comment (johnsoncodehk) [reply src/index.ts]: Updated.

File: tests/components/WithTeleportEmitsComp.vue [hunk 4]
```diff
@@ -1,6 +1,8 @@
 <template>
   <teleport to="#somewhere">
-    <emits-event msg="hi there" />
+    <emits-event />
+    <!-- avoid vue-tsc unknown prop bug for now -->
+    <!-- <emits-event msg="hi there" /> -->
```
[the remark this answers is not in the document]
Comment (johnsoncodehk) [reply tests/components/WithTeleportEmitsComp.vue:5]: Updated.

File: src/vueWrapper.ts (hunk 2 above)
Comment (johnsoncodehk) [reply src/vueWrapper.ts]: Yes, and I've updated to make it more explicit.

**Comment by johnsoncodehk** [comment]
Also merged the remaining overloads, since this is a breaking change anyway.

Compared with the original PR, the change may be quite radical now, if this does not meet expectations, please feel free to revert [`3228334`](https://github.com/vuejs/test-utils/pull/2026/commits/322833427ce455dc5115b40283964313bd581397).

**Comment by lmiller1990** [comment]
Thanks @johnsoncodehk - please give us a bit to figure out how to handle a breaking change. We haven't had one before, so we don't have a process around it, but we can do so if it'll improve the library for everyone.

**Review by cexbrayat — APPROVED** [review]

**Comment by cexbrayat** [comment]
Changes look good to me.
Once merged, maybe we could cut a 2.4 alpha release to see if that deserves a 3.0 release or not?
We'll also be able to check if that fixes #1973 and the bump to TS v5

**Comment by pikax** [comment]
It simplifies a lot, but there's some broken things:
```ts
const a = mount(
  defineComponent({
    props: ['hello'],
    data() {
      return {
        a: 1
      }
    },
    computed: {
      b() {
        return 0
      }
    }
  }),
  {
    data() {
      return {
        b: 12 // this should break the component since is not data
      }
    }
  }
)
```

On this PR:
image

Main branch:
image

**Comment by johnsoncodehk** [comment]
@pikax thanks for reporting that, can you try this latest commit?

Since I haven't worked on this repo in the past, these modifications may be rather naive, please feel free to edit the PR if found something else breaks.

**Review by freakzlike — APPROVED** [review]
LGTM 👍
